export const ANALYTICS_EVENTS = [
  "VENDOR_REGISTRATION_STARTED",
  "VENDOR_REGISTERED",
  "PRODUCT_CREATED",
  "PRODUCT_SEARCHED",
  "PRODUCT_VIEWED",
  "ORDER_STARTED",
  "ORDER_CONFIRMED",
  "ORDER_ACCEPTED",
  "ORDER_DECLINED",
  "ORDER_READY",
  "ORDER_COMPLETED",
  "ORDER_CANCELLED",
  "SUPPORT_REQUESTED",
] as const;

export type AnalyticsEventName = (typeof ANALYTICS_EVENTS)[number];
