export const CONVERSATION_STATES = [
  "NEW",
  "MAIN_MENU",
  "VENDOR_REGISTRATION_NAME",
  "VENDOR_REGISTRATION_BUSINESS",
  "VENDOR_REGISTRATION_CATEGORY",
  "VENDOR_REGISTRATION_LOCATION",
  "VENDOR_REGISTRATION_LANGUAGE",
  "VENDOR_REGISTRATION_CONFIRM",
  "VENDOR_MENU",
  "ADD_PRODUCT_NAME",
  "ADD_PRODUCT_QUANTITY",
  "ADD_PRODUCT_UNIT",
  "ADD_PRODUCT_PRICE",
  "ADD_PRODUCT_IMAGE",
  "ADD_PRODUCT_CONFIRM",
  "CUSTOMER_MENU",
  "SEARCH_PRODUCT_QUERY",
  "SEARCH_LOCATION",
  "SEARCH_RESULTS",
  "ORDER_QUANTITY",
  "ORDER_CONFIRM",
  "ORDER_WAITING_VENDOR",
  "SUPPORT",
] as const;

export type ConversationState = (typeof CONVERSATION_STATES)[number];

export const MESSAGE_DIRECTIONS = ["INBOUND", "OUTBOUND"] as const;

export type MessageDirection = (typeof MESSAGE_DIRECTIONS)[number];
